config/routes.rb
Rails.application.routes.draw do
  resources :madlibs
  get '/madlibs/:id/mad', to: 'madlibs#madlib', as: :lib
  post '/madlibs/:id/mad', to: 'madlibs#libbed'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/madlib.rb
class Madlib < ApplicationRecord

    def blanks
        template.scan(/\[.*?\]/)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/madlibs_controller.rb
class MadlibsController < ApplicationController
  before_action :set_madlib, only: %i[ show edit update destroy madlib libbed ]

  # GET /madlibs or /madlibs.json
  def index
    @madlibs = Madlib.all
  end

  # GET /madlibs/1 or /madlibs/1.json
  def show
  end

  # GET /madlibs/new
  def new
    @madlib = Madlib.new
  end

  # GET /madlibs/1/edit
  def edit
  end

  # POST /madlibs or /madlibs.json
  def create
    @madlib = Madlib.new(madlib_params)

    respond_to do |format|
      if @madlib.save
        format.html { redirect_to madlib_url(@madlib), notice: "Madlib was successfully created." }
        format.json { render :show, status: :created, location: @madlib }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @madlib.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /madlibs/1 or /madlibs/1.json
  def update
    respond_to do |format|
      if @madlib.update(madlib_params)
        format.html { redirect_to madlib_url(@madlib), notice: "Madlib was successfully updated." }
        format.json { render :show, status: :ok, location: @madlib }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @madlib.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /madlibs/1 or /madlibs/1.json
  def destroy
    @madlib.destroy

    respond_to do |format|
      format.html { redirect_to madlibs_url, notice: "Madlib was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def madlib
    @blanks = @madlib.blanks    
  end

  def libbed
    @story =  @madlib.template
    @madlib.blanks.each_with_index do |section, index|
     puts section
     puts @story
      @story.sub!(section, params[index.to_s])
    end
    respond_to do |format|
     
        format.html { render :libbed, status: :unprocessable_entity }
        format.json { render json: @madlib.errors, status: :unprocessable_entity }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_madlib
      @madlib = Madlib.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def madlib_params
      params.require(:madlib).permit(:name, :template)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/madlibs_helper.rb
module MadlibsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Madlibs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/madlibs/_form.html.erb
<%= form_with(model: madlib) do |form| %>
  <% if madlib.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(madlib.errors.count, "error") %> prohibited this madlib from being saved:</h2>

      <ul>
        <% madlib.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :template, style: "display: block" %>
    <%= form.text_area :template %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/madlibs/_madlib.html.erb
<div id="<%= dom_id madlib %>">
  <p>
    <strong>Name:</strong>
    <%= madlib.name %>
  </p>

  <p>
    <%# <strong>Template:</strong> %>
    <%# <%= madlib.template %>
  </p>

</div>

app/views/madlibs/edit.html.erb
<h1>Editing madlib</h1>

<%= render "form", madlib: @madlib %>

<br>

<div>
  <%= link_to "Show this madlib", @madlib %> |
  <%= link_to "Back to madlibs", madlibs_path %>
</div>

app/views/madlibs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Madlibs</h1>

<div id="madlibs">
  <% @madlibs.each do |madlib| %>
    <%= render madlib %>
    <p>
      <%= link_to "Show this madlib", lib_path(madlib) %>
    </p>
  <% end %>
</div>

<%= link_to "New madlib", new_madlib_path %>

app/views/madlibs/libbed.html.erb
<h1>Madlibbing madlib</h1>



    <div style="color: green">
      <p><%= @story %> </p>
    
      
    </div>

  


<br>

<div>
  <%= link_to "Show this madlib", @madlib %> |
  <%= link_to "Back to madlibs", madlibs_path %>
</div>

app/views/madlibs/madlib.html.erb
<h1>Madlibbing madlib</h1>

<%= form_with do |form| %>
  <% @blanks.each_with_index do |blank, index| %>
    <div style="color: red">
      <h2><%= blank %> </h2>
      <%= form.text_field index %>
      
    </div>
  <% end %>

  

  <div>
    <%= form.submit %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Show this madlib", @madlib %> |
  <%= link_to "Back to madlibs", madlibs_path %>
</div>

app/views/madlibs/new.html.erb
<h1>New madlib</h1>

<%= render "form", madlib: @madlib %>

<br>

<div>
  <%= link_to "Back to madlibs", madlibs_path %>
</div>

app/views/madlibs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @madlib %>

<div>
  <%= link_to "Edit this madlib", edit_madlib_path(@madlib) %> |
  <%= link_to "Back to madlibs", madlibs_path %>

  <%= button_to "Destroy this madlib", @madlib, method: :delete %>
</div>